# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ebd027fb55d5aae6f786673c33724275b1dab7366af4fbea55196ef66f237a61a0bdc4072361880edbf1b5015bfcb6a401bb9c7bc6a6f122f08b863b3c0a7c74

test:
  secret_key_base: 3b35d033172f7c7f7c61179df83b6e9be769f92fbb613a83c0c7c0f43ffa801769512816109b8524f6f1210f50c9d9fa5d87211dd65fa331059b80a94b4ac665

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
